function genertateList() {
    var numberInput = document.getElementById("numberInput")
    var resultList = [];

    for (var i = 0; i <= numberInput; i++) {
    if (containsDigit)(i, 3)) {
             resultList.push ("Won't you be my neighbor?");
        } else if (containsDigit(i, 2)) {
            resultList.push("Boop!");
        } else if (containDigit(i, 1)) {
            resultList.push("Beep!"); 
        } else {
            resultList.push(i);
        }
}